_wandb:
    value:
        cli_version: 0.21.0
        e:
            rarwcl6p7ud8gt9oqcxhkbtabc67skx3:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 80
                cpu_count_logical: 160
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "83845120000"
                        used: "30276780032"
                email: bl3912@nyu.edu
                executable: /scratch/bl3912/venv/prompt-da/bin/python
                git:
                    commit: 57caa6bb24f8d58abe9feaa0aa6d014fd6be514f
                    remote: https://github.com/bingxuan-li/PromptDA.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-3851c007-9c20-8957-6ff9-36d6fd59ed5c
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-015d8dfe-cf84-b2b5-7f14-2e1d1959b356
                host: ga033.hpc.nyu.edu
                memory:
                    total: "1081271287808"
                os: Linux-5.14.0-284.86.1.el9_2.x86_64-x86_64-with-glibc2.34
                program: /home/bl3912/code/PromptDA/train.py
                python: CPython 3.11.13
                root: /home/bl3912/code/PromptDA
                slurm:
                    job_id: "63539353"
                startedAt: "2025-07-09T16:38:56.668010Z"
                writerId: rarwcl6p7ud8gt9oqcxhkbtabc67skx3
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 103
                - 105
            "3":
                - 13
                - 61
            "4": 3.11.13
            "5": 0.21.0
            "6": 4.52.4
            "12": 0.21.0
            "13": linux-x86_64
